spring:
    application:
        name: config-server-service
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations

server:
    port: 8086