services:
    db-mongo:
        image: mongo:latest
        container_name: db-mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
        driver: local