services:
    db-mongo:
        image: mongo:latest
        container_name: db-mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    pqc-redis:
        image: redis:latest
        container_name: pqc-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    mongo_data:
        driver: local
    redis_data:
        driver: local