version: '3.8'

services:
    db-mongo:
        image: mongo:latest
        container_name: db-mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    pqc-redis:
        image: redis:latest
        container_name: pqc-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    pqc-kafka:
        image: confluentinc/cp-kafka:latest
        container_name: pqc-kafka
        hostname: pqc-kafka
        restart: unless-stopped
        ports:
            # Port for host machine to connect (e.g. with a UI tool)
            - "9094:9094"
            # Note: Port 9092 is used for inter-container communication and is not exposed to the host
        volumes:
            - kafka_data:/var/lib/kafka/data

volumes:
    mongo_data:
        driver: local
    redis_data:
        driver: local
    kafka_data:
        driver: local