server:
    port: 8083 # Port for the pqc-service

# 1. Enable Virtual Threads
spring:
    threads:
        virtual:
            enabled: true

    # 2. MongoDB Database
    data:
        mongodb:
            uri: mongodb://${PQC_SERVICE_MONGO_HOST:localhost}:${PQC_SERVICE_MONGO_PORT:27017}
            database: ${PQC_SERVICE_MONGO_DB:pqc_keys_db}

    # 3. Security: Needs client ID/Secret to deserialize the user
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${GITHUB_CLIENT_ID}
                        client-secret: ${GITHUB_CLIENT_SECRET}

# 4. Eureka client configuration
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/