server:
    port: 8083 # Port for the pqc-service

# 1. Enable Virtual Threads
spring:
    threads:
        virtual:
            enabled: true

    # 2. MongoDB Database
    data:
        mongodb:
            uri: mongodb://${PQC_SERVICE_MONGO_HOST:localhost}:${PQC_SERVICE_MONGO_PORT:27017}
            database: ${PQC_SERVICE_MONGO_DB:pqc_keys_db}

    # 3. Security Configuration for OAuth2 Resource Server with JWT
    security:
        oauth2:
            resourceserver:
                jwt:
                    # This Uri points to the public key endpoint of the gateway service
                    jwk-set-uri: http://${GATEWAY_SERVICE_HOST:localhost}:${GATEWAY_SERVICE_PORT}/.well-known/jwks.json

# 4. Eureka client configuration
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/