server:
    port: 8081

spring:
    threads:
        virtual:
            enabled: true

    data:
        mongodb:
            uri: mongodb://${USER_SERVICE_MONGO_HOST:localhost}:${USER_SERVICE_MONGO_PORT:27017}
            database: ${USER_SERVICE_MONGO_DB:users_db}

        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}

    session:
        store-type: redis
        redis:
            namespace: "pqcstego:sessions" # Must match the Gateway's configuration

    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${GITHUB_CLIENT_ID}
                        client-secret: ${GITHUB_CLIENT_SECRET}

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/